name: GitHub Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11' # Replace with your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Create necessary directories
        run: mkdir -p build/app/intermediates/flutter/release/arm64-v8a

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
